[build]
  base    = "docs"
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.85.0"

[context.deploy-preview] # merge-requests
  command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]  # branches
  command = "hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"