apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dockhandsecrets.dockhand.boxboat.io
  labels:
    app.kubernetes.io/name: dockhandprofiles.dockhand.boxboat.io
    {{- include "dockhand-secrets-operator.labels" . | nindent 4 }}
spec:
  group: dockhand.boxboat.io
  scope: Namespaced
  names:
    plural: dockhandsecrets
    singular: dockhandsecret
    kind: DockhandSecret
    shortNames:
      - dhs
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            dockhandProfile:
              type: string
              description: |-
                Name of the DockhandConfig to use for this secret
            secretName:
              type: string
              description: |-
                Name of the secret that will be created or updated with the processed contents of the data field.
            data:
              type: object
              description: |-
                Store arbitrary templated secret data here just as you would in a kubernetes configmap.
                The dockhand-secrets-operator will retrieve the secrets from the secrets backend and create normal
                kubernetes secrets for use by your application. Secrets should be templated using go templating with
                alternative delimiters << >> rather than \{\{ \}\}.
              additionalProperties:
                type: string
      subresources:
        status: {}
