---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-controller-sa-cluster-role
rules:
  - apiGroups: [ "*" ]
    resources:
      - events
      - secrets
      - daemonsets
      - deployments
      - statefulsets
      - dockhandsecrets
      - dockhandsecretsprofiles
    verbs:
      - get
      - delete
      - create
      - patch
      - update
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-controller-sa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dockhand-secrets-operator.name" . }}-controller-sa-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "dockhand-secrets-operator.name" . }}-controller-sa
    namespace: {{ .Release.Namespace }}
