---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-webhook-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-webhook-sa-cluster-role
rules:
  - apiGroups:
     -  admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - create
      - patch
      - update
      - list
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
    verbs:
      - get
      - create
      - delete
      - list
      - watch
  - apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests/approval
    verbs:
      - update
  - apiGroups:
      - certificates.k8s.io
    resources:
      - signers
    resourceNames:
      - kubernetes.io/*
    verbs:
      - approve
  - apiGroups: [ "" ]
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
      - update
      - list
  - apiGroups: [ "" ]
    resources:
      - configmaps
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dockhand-secrets-operator.name" . }}-webhook-sa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dockhand-secrets-operator.name" . }}-webhook-sa-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ include "dockhand-secrets-operator.name" . }}-webhook-sa
    namespace: {{ .Release.Namespace }}
