version: '3.7'

services:
  hugo:
    image: jojomi/hugo:0.85.0
    container_name: dockhand-secrets-operator-docs
    volumes:
      - ./:/src
    entrypoint:
      - hugo
    command:
      - serve
      - --baseURL=http://localhost:${PORT:-1313}/
      - --bind=0.0.0.0
      - --buildDrafts
      - --port=${PORT:-1313}
      - "${POLL_ARG:---watch}"
    ports:
      - "${PORT:-1313}:${PORT:-1313}"
