name: pre-commit

on:
  pull_request:
  # push:
  #   branches: '**'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1
